In [7]:
import json
import os

import pandas as pd

# --- Local (with a .env file) ---
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.environ["GROQ_API_KEY"]


# TODO: set API_KEY using ONE of the methods above.

# OpenAI-compatible client (works for Groq and OpenAI; Gemini users see their docs):
from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1",   # remove this line if using OpenAI itself
)
MODEL = "llama-3.3-70b-versatile"                # or your provider's model name

print("Client ready.")

Client ready.

In [8]:
# TODO: Write a helper function you will reuse for the WHOLE lab:
#
def ask_llm(user_prompt, system_prompt="You are a helpful assistant.",
            temperature=0.7, max_tokens=500):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response
#
# TODO: Call it once with a simple question and print the answer.
response = ask_llm("What is doppler effect?")
print(response.choices[0].message.content)

# TODO: Print response.usage as well — how many tokens did your call consume?
print(response.usage)

The Doppler effect is a phenomenon in physics that describes how the frequency of a wave changes when its source is moving relative to an observer. This effect is named after Christian Doppler, who first described it in 1842.

The Doppler effect occurs when a wave, such as sound or light, is emitted by a source that is moving towards or away from an observer. When the source is moving towards the observer, the frequency of the wave increases, and when it is moving away, the frequency decreases.

Here's a simple explanation:

1. **Source moving towards the observer**: The waves are compressed, resulting in a higher frequency (or pitch) and a shorter wavelength.
2. **Source moving away from the observer**: The waves are stretched, resulting in a lower frequency (or pitch) and a longer wavelength.

The Doppler effect is commonly observed in various situations, such as:

* **Police sirens**: When a police car is approaching, its siren sounds higher pitched, and when it's moving away, the pitch is lower.
* **Astronomy**: The light from stars and galaxies can be shifted towards the red end of the spectrum (redshift) if they are moving away from us, or towards the blue end (blueshift) if they are moving towards us.
* **Radar technology**: The Doppler effect is used in radar systems to measure the speed of moving objects, such as aircraft or vehicles.
* **Medical imaging**: The Doppler effect is used in ultrasound technology to measure blood flow and detect vascular diseases.

The Doppler effect has many practical applications in fields like physics, astronomy, engineering, and medicine, and it's an essential concept in understanding the behavior of waves and their interactions with moving objects.
CompletionUsage(completion_tokens=355, prompt_tokens=47, total_tokens=402, completion_tokens_details=None, prompt_tokens_details=None, queue_time=0.05239652, prompt_time=0.001446156, completion_time=1.231478018, total_time=1.232924174)

## Student Reasoning — Anatomy of a Call

**1. Difference between system and user**

- **system**: Tells the AI how to behave or what role to take.
  - Example: `"You are a helpful math tutor."`
- **user**: Contains the actual question or instruction we want the AI to respond to.
  - Example: `"Simple explain what eigenvalues and eigenvectors are."`

**2. What is a token?**

A **token** is a small piece of text that an LLM processes, such as a word, or part of a word.

**Why do API providers bill per token rather than per request?**

API providers bill per token because **different requests use different amounts of text**. Tokens provide a better measure of how much the model processes and generates.

In [9]:
# TODO: Ask the SAME question 5 times at temperature=0.0
# and 5 times at temperature=1.2.

# TODO: Print all 10 answers, grouped by temperature.
question = "What is core banking system?"

print("--- Temperature 0.0 ---")
for i in range(5):
  answer = ask_llm(question, temperature=0.0)
  print(f"{i + 1}. {answer.choices[0].message.content}")

print("\n--- Temperature 1.2 ---")
for i in range(5):
  answer = ask_llm(question, temperature=1.2)
  print(f"{i + 1}. {answer.choices[0].message.content}")

--- Temperature 0.0 ---
1. A core banking system (CBS) is a software application that enables banks and other financial institutions to manage their daily operations, customer accounts, and financial transactions efficiently. It is the backbone of a bank's information technology (IT) infrastructure, providing a centralized platform for processing transactions, managing accounts, and delivering banking services to customers.

A core banking system typically includes the following features:

1. **Account management**: CBS allows banks to create, manage, and maintain customer accounts, including deposit accounts, loan accounts, and credit card accounts.
2. **Transaction processing**: CBS enables banks to process various types of transactions, such as deposits, withdrawals, transfers, and payments.
3. **Payment processing**: CBS facilitates payment processing, including check clearing, electronic funds transfer (EFT), and online payment processing.
4. **Loan management**: CBS provides tools for managing loan accounts, including loan origination, disbursement, and repayment tracking.
5. **Customer relationship management**: CBS helps banks to manage customer relationships, including customer profiling, account management, and customer service.
6. **Reporting and analytics**: CBS provides real-time reporting and analytics, enabling banks to monitor their operations, track customer behavior, and make informed decisions.
7. **Security and compliance**: CBS ensures the security and integrity of customer data, while also complying with regulatory requirements, such as anti-money laundering (AML) and know-your-customer (KYC) regulations.

The benefits of a core banking system include:

1. **Improved efficiency**: CBS automates many banking processes, reducing manual errors and increasing productivity.
2. **Enhanced customer experience**: CBS enables banks to provide 24/7 online banking services, mobile banking, and other digital channels, improving customer convenience and satisfaction.
3. **Increased scalability**: CBS allows banks to grow their business, expand their customer base, and increase their transaction volumes without compromising performance.
4. **Better risk management**: CBS provides real-time monitoring and reporting, enabling banks to identify and mitigate risks more effectively.
5. **Cost savings**: CBS helps banks to reduce operational costs, minimize manual errors, and optimize their IT infrastructure.

Overall, a core banking system is a critical component of a bank's IT infrastructure, enabling it to provide efficient, secure, and customer-centric banking services.
2. A core banking system (CBS) is a software application that enables banks and other financial institutions to manage their daily operations, customer accounts, and financial transactions efficiently. It is the backbone of a bank's information technology (IT) infrastructure and provides a centralized platform for processing transactions, managing accounts, and delivering banking services to customers.

A core banking system typically includes the following features:

1. **Account management**: CBS allows banks to create, manage, and maintain customer accounts, including deposit accounts, loan accounts, and credit card accounts.
2. **Transaction processing**: CBS enables banks to process various types of transactions, such as deposits, withdrawals, transfers, and payments.
3. **Payment processing**: CBS facilitates payment processing, including check clearing, electronic funds transfer (EFT), and online payment processing.
4. **Loan management**: CBS provides tools for managing loan accounts, including loan origination, disbursement, and repayment tracking.
5. **Customer relationship management**: CBS helps banks to manage customer relationships, including customer profiling, account management, and customer service.
6. **Reporting and analytics**: CBS provides real-time reporting and analytics capabilities, enabling banks to monitor their operations, track customer behavior, and make informed decisions.
7. **Security and compliance**: CBS ensures the security and integrity of customer data and transactions, while also complying with regulatory requirements and industry standards.

The benefits of a core banking system include:

1. **Improved efficiency**: CBS automates many banking processes, reducing manual errors and increasing productivity.
2. **Enhanced customer experience**: CBS enables banks to provide 24/7 online banking services, mobile banking, and other digital channels, improving customer convenience and satisfaction.
3. **Increased scalability**: CBS allows banks to grow their business and expand their customer base without significant increases in operational costs.
4. **Better risk management**: CBS provides real-time monitoring and reporting capabilities, enabling banks to identify and manage risks more effectively.
5. **Compliance with regulations**: CBS helps banks to comply with regulatory requirements and industry standards, reducing the risk of non-compliance and associated penalties.

Overall, a core banking system is a critical component of a bank's IT infrastructure, enabling it to provide efficient, secure, and customer-centric banking services.
3. A core banking system (CBS) is a software application that enables banks and financial institutions to manage their daily operations, customer accounts, and financial transactions efficiently. It is the backbone of a bank's information technology (IT) infrastructure, providing a centralized platform for processing transactions, managing accounts, and delivering banking services to customers.

A core banking system typically includes the following features:

1. **Account management**: CBS allows banks to create, manage, and maintain customer accounts, including deposit accounts, loan accounts, and credit card accounts.
2. **Transaction processing**: CBS enables banks to process various types of transactions, such as deposits, withdrawals, transfers, and payments.
3. **Payment processing**: CBS facilitates payment processing, including check clearing, electronic funds transfer (EFT), and online payment processing.
4. **Loan management**: CBS provides tools for managing loan accounts, including loan origination, disbursement, and repayment tracking.
5. **Customer relationship management**: CBS helps banks to manage customer relationships, including customer profiling, account management, and customer service.
6. **Reporting and analytics**: CBS provides real-time reporting and analytics, enabling banks to monitor their operations, track customer behavior, and make informed decisions.
7. **Security and compliance**: CBS ensures the security and integrity of customer data, while also complying with regulatory requirements, such as anti-money laundering (AML) and know-your-customer (KYC) regulations.

The benefits of a core banking system include:

1. **Improved efficiency**: CBS automates many banking processes, reducing manual errors and increasing productivity.
2. **Enhanced customer experience**: CBS enables banks to provide 24/7 banking services, including online and mobile banking, making it more convenient for customers to manage their accounts.
3. **Increased scalability**: CBS allows banks to grow their customer base and expand their services without compromising on performance.
4. **Better risk management**: CBS provides real-time monitoring and reporting, enabling banks to identify and mitigate potential risks.
5. **Cost savings**: CBS helps banks to reduce operational costs by automating processes, minimizing manual interventions, and optimizing resource utilization.

Overall, a core banking system is a critical component of a bank's IT infrastructure, enabling it to provide efficient, secure, and customer-centric banking services.
4. A core banking system (CBS) is a software application that enables banks and other financial institutions to manage their daily operations, customer accounts, and financial transactions efficiently. It is the backbone of a bank's information technology (IT) infrastructure and provides a centralized platform for processing transactions, managing accounts, and delivering banking services to customers.

A typical core banking system includes the following components:

1. **Account management**: CBS manages customer accounts, including account opening, account maintenance, and account closure.
2. **Transaction processing**: CBS processes various types of transactions, such as deposits, withdrawals, transfers, and payments.
3. **Ledger management**: CBS maintains a centralized ledger that records all transactions, allowing for real-time updates and reconciliation.
4. **Loan management**: CBS manages loan accounts, including loan origination, loan servicing, and loan repayment.
5. **Deposit management**: CBS manages deposit accounts, including term deposits, savings accounts, and current accounts.
6. **Payment processing**: CBS processes payments, including checks, electronic funds transfers (EFTs), and credit card transactions.
7. **Reporting and analytics**: CBS provides reporting and analytics tools to help banks analyze customer behavior, transaction patterns, and financial performance.

The benefits of a core banking system include:

1. **Improved efficiency**: CBS automates many banking processes, reducing manual errors and increasing productivity.
2. **Enhanced customer experience**: CBS enables banks to offer a range of services, including online banking, mobile banking, and ATM services, making it easier for customers to manage their accounts.
3. **Better risk management**: CBS provides real-time monitoring and reporting, enabling banks to identify and manage risks more effectively.
4. **Increased scalability**: CBS can handle large volumes of transactions and customer data, making it easier for banks to grow and expand their operations.
5. **Compliance with regulations**: CBS helps banks comply with regulatory requirements, such as anti-money laundering (AML) and know-your-customer (KYC) regulations.

Overall, a core banking system is a critical component of a bank's IT infrastructure, enabling it to provide efficient, secure, and reliable banking services to its customers.
5. A core banking system (CBS) is a software application that enables banks and other financial institutions to manage their daily operations, customer accounts, and financial transactions efficiently. It is the backbone of a bank's information technology (IT) infrastructure, providing a centralized platform for processing transactions, managing accounts, and delivering banking services to customers.

A typical core banking system includes the following components:

1. **Account management**: CBS manages customer accounts, including account opening, account maintenance, and account closure.
2. **Transaction processing**: CBS processes various types of transactions, such as deposits, withdrawals, transfers, and payments.
3. **Ledger management**: CBS maintains a centralized ledger that records all transactions, ensuring that accounts are updated in real-time.
4. **Security and compliance**: CBS ensures the security and integrity of customer data, complying with regulatory requirements and industry standards.
5. **Reporting and analytics**: CBS provides reporting and analytics tools to help banks analyze customer behavior, track transactions, and make informed decisions.

The key benefits of a core banking system include:

1. **Improved efficiency**: Automates manual processes, reducing errors and increasing productivity.
2. **Enhanced customer experience**: Provides 24/7 access to banking services through various channels, such as online banking, mobile banking, and ATMs.
3. **Increased scalability**: Supports growth and expansion, enabling banks to handle a large volume of transactions and customer accounts.
4. **Better risk management**: Helps banks to identify and mitigate risks, such as fraud and credit risk, through advanced analytics and reporting.
5. **Compliance with regulations**: Ensures adherence to regulatory requirements, reducing the risk of non-compliance and associated penalties.

Examples of core banking systems include:

1. Temenos T24
2. SAP for Banking
3. Oracle FLEXCUBE
4. Finacle (from Infosys)
5. Misys FusionBanking

In summary, a core banking system is a critical component of a bank's IT infrastructure, enabling efficient, secure, and compliant management of customer accounts, transactions, and banking services.

--- Temperature 1.2 ---
1. A core banking system (CBS) is a computerized system used by banks to manage their daily operations, including customer accounts, transactions, and financial data. It is the central nervous system of a bank, providing a platform for banks to process transactions, manage accounts, and offer various banking services to their customers.

Key features and functions of a core banking system:

1. **Account management**: CBS allows banks to create, maintain, and manage customer accounts, including savings, current, and loan accounts.
2. **Transaction processing**: It enables banks to process various types of transactions, such as deposits, withdrawals, transfers, and payments.
3. **General ledger**: CBS maintains a general ledger that tracks all financial transactions, providing a real-time view of the bank's financial position.
4. **Reporting and analytics**: It generates reports and provides analytics on customer behavior, transaction patterns, and financial performance.
5. **Security and compliance**: CBS includes security features, such as access controls, encryption, and audit trails, to ensure the integrity and confidentiality of customer data.
6. **Integration with other systems**: It can integrate with other banking systems, such as online banking, mobile banking, and ATM systems.
7. **Customer relationship management**: CBS can help banks manage customer relationships, including customer profiling, segmentation, and targeted marketing.

Benefits of a core banking system:

1. **Improved efficiency**: Automates many banking processes, reducing manual errors and increasing processing speed.
2. **Enhanced customer experience**: Provides customers with access to their accounts and banking services through various channels, such as online and mobile banking.
3. **Increased accuracy**: Minimizes errors and ensures that customer data is up-to-date and accurate.
4. **Better risk management**: Enables banks to monitor and manage risk more effectively, including credit risk, operational risk, and compliance risk.
5. **Scalability and flexibility**: Can be easily scaled up or down to meet changing business needs, and can be integrated with new technologies and systems.

In summary, a core banking system is a critical component of a bank's operations, providing a centralized platform for managing customer accounts, transactions, and financial data. Its key features and functions enable banks to improve efficiency, enhance customer experience, and manage risk more effectively.
2. A core banking system (CBS) is a centralized software system that enables banks and financial institutions to manage their core operations and transactions efficiently. It is the backbone of a bank's IT infrastructure, providing a platform for processing various banking transactions, managing customer accounts, and maintaining financial records.

The primary function of a core banking system is to:

1. **Manage customer accounts**: CBS stores and manages account information, including account types, balances, and transaction history.
2. **Process transactions**: It facilitates various transactions, such as deposits, withdrawals, transfers, and loans, in real-time or batch mode.
3. **Maintain ledgers and journals**: CBS updates account ledgers, journals, and financial statements to ensure accurate and up-to-date financial records.
4. **Support online banking and mobile banking**: Many core banking systems provide interfaces for online and mobile banking, allowing customers to access their accounts and perform transactions remotely.
5. **Comply with regulatory requirements**: CBS helps banks meet regulatory requirements, such as anti-money laundering (AML) and know-your-customer (KYC) regulations.

Typical features of a core banking system include:

* Account management
* Transaction processing
* Payment processing
* Loan management
* Credit scoring
* Reporting and analytics
* Security and risk management
* Compliance management

Core banking systems can be implemented in various ways, including:

1. **In-house development**: Banks can develop their own core banking system using in-house resources.
2. **Commercial off-the-shelf (COTS) software**: Banks can purchase pre-built core banking systems from vendors.
3. **Cloud-based solutions**: Cloud-based core banking systems offer a scalable and cost-effective alternative to traditional on-premise solutions.
4. **Outsourced services**: Banks can outsource their core banking operations to third-party service providers.

The benefits of a core banking system include:

* Improved operational efficiency
* Enhanced customer experience
* Increased accuracy and reliability
* Better risk management
* Regulatory compliance
* Cost savings

However, implementing a core banking system can be complex and time-consuming, requiring significant investment in technology, training, and process improvements.
3. A core banking system (CBS) is a software application that enables banks and financial institutions to manage their daily operations, customer accounts, and financial transactions. It is the central system that supports all banking activities, providing a single, unified platform for managing customer information, accounts, transactions, and banking services.

A core banking system typically includes the following components:

1. **Account management**: managing customer accounts, including deposit accounts, loan accounts, and credit card accounts.
2. **Transaction processing**: processing financial transactions, such as deposits, withdrawals, transfers, and payments.
3. **Payment clearing and settlement**: facilitating the exchange of funds between banks and financial institutions.
4. **Customer information management**: storing and managing customer demographic and account information.
5. **Loan and credit management**: managing loan and credit products, including loan origination, servicing, and collection.
6. **Security and access control**: ensuring the security and integrity of customer data and preventing unauthorized access.
7. **Compliance and reporting**: generating reports and complying with regulatory requirements.

The core banking system is usually integrated with other banking systems, such as:

1. **Online banking systems**: enabling customers to access their accounts and conduct transactions online.
2. **Mobile banking systems**: allowing customers to access their accounts and conduct transactions through mobile devices.
3. **ATM and card management systems**: managing ATM and card transactions.
4. **Treasury management systems**: managing the bank's own financial operations, such as investments and liquidity management.

The benefits of a core banking system include:

1. **Improved customer service**: providing customers with easy access to their accounts and enabling them to conduct transactions efficiently.
2. **Increased operational efficiency**: automating many banking processes, reducing manual errors and improving productivity.
3. **Enhanced security and risk management**: protecting customer data and preventing unauthorized access.
4. **Better decision-making**: providing banks with accurate and timely information to support strategic decision-making.
5. **Scalability and flexibility**: enabling banks to grow and adapt to changing market conditions and customer needs.


## Student Reasoning — Temperature

- **Temperature = 0.0:** The answers were very similar. The model consistently explained core banking systems using almost the same structure and ideas.


- **Temperature = 1.2:** The answers were more varied. The model used different wording, examples, and structures, and one response even reached the `max_tokens` limit.

For the **loan decision-support system**, a **low temperature (around 0.0–0.3)** is more appropriate because decisions should be consistent, predictable, and less influenced by randomness.

In [10]:
LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

# Gold-standard labels for three letters (for Section 4 evaluation):
GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

6 letters loaded.

In [11]:
# TODO: Write SUMMARY_PROMPT_V1 — your first, naive attempt (e.g. just "Summarize this:").
SUMMARY_PROMPT_V1 = "Summarize this:"

#   Run it on L002 and L006. Read the output critically.
for letter_id in ["L002", "L006"]:
    response = ask_llm(
        f"{SUMMARY_PROMPT_V1}\n\n{LETTERS[letter_id]}"
    )
    print(f"\n--- {letter_id} ---")
    print(response.choices[0].message.content)


# TODO: Now write SUMMARY_PROMPT_V2 as a proper template with:
SUMMARY_SYSTEM_V2 = """You are an assistant to a microfinance loan officer.
Summarize loan applications factually and neutrally.
Do not invent or assume any details.
Keep the summary to 3-4 sentences."""

SUMMARY_PROMPT_V2 = "Summarize this loan application:\n\n{letter_text}"
#   - a system prompt giving the LLM a ROLE (e.g. "You are an assistant to a microfinance
#     loan officer...") and constraints (factual, neutral, no invented details, 3-4 sentences)
#   - a user prompt template like: f"Summarize this loan application:\n\n{letter_text}"
#   Run V2 on the same two letters at temperature=0.
for letter_id in ["L002", "L006"]:
    response = ask_llm(
        SUMMARY_PROMPT_V2.format(letter_text=LETTERS[letter_id]),
        system_prompt=SUMMARY_SYSTEM_V2,
        temperature=0.0
    )
    print(f"\n--- {letter_id} ---")
    print(response.choices[0].message.content)

# TODO: Compare V1 vs V2 outputs side by side. Keep both prompt versions in this notebook.
for letter_id in ["L002", "L006"]:
    v1 = ask_llm(
        f"{SUMMARY_PROMPT_V1}\n\n{LETTERS[letter_id]}"
    )
    
    v2 = ask_llm(
        SUMMARY_PROMPT_V2.format(letter_text=LETTERS[letter_id]),
        system_prompt=SUMMARY_SYSTEM_V2,
        temperature=0.0
    )

    print(f"\n========== {letter_id} ==========")
    print("\nV1:")
    print(v1.choices[0].message.content)
    
    print("\nV2:")
    print(v2.choices[0].message.content)

--- L002 ---
Kwame Boateng, a commercial driver in Kumasi, is seeking a loan of GHS 25,000 to repair his vehicle's engine and pay off personal debts. He's experiencing a slow period in business, but expects it to improve after the festive season, and is willing to repay the loan when he can. However, he currently has no collateral to offer.

--- L006 ---
Kofi, a 22-year-old, is seeking a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business from Dubai. He has no prior experience, but claims to be "business-minded" based on his friends' opinions. He promises to repay the loan within a year, once his businesses are successful, with no collateral offered, relying on his personal guarantee of being "trustworthy".

--- L002 ---
Kwame Boateng, a commercial driver in Kumasi, has applied for a loan of GHS 25,000. He intends to use the funds to repair his trotro engine and settle personal debts. Mr. Boateng mentions that his business has been slow, but expects it to improve after the festive season. He does not have collateral to offer at this time.

--- L006 ---
Kofi has applied for a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business. He is 22 years old and claims to be business-minded, although he has not yet started any of these ventures. Kofi intends to repay the loan within one year, expecting his businesses to be successful by then. He does not have collateral to offer, but assures that he is trustworthy.

========== L002 ==========

V1:
Kwame Boateng, a commercial driver in Kumasi, is seeking a loan of GHS 25,000 to repair his vehicle's engine and pay off personal debts. He's experiencing a slow period in business but is optimistic it will improve after the festive season, and is willing to repay the loan when he can. However, he doesn't have any collateral to offer at the moment.

V2:
Kwame Boateng, a commercial driver in Kumasi, has applied for a loan of GHS 25,000. He intends to use the funds to repair his trotro engine and settle personal debts. Mr. Boateng mentions that his business has been slow, but expects it to improve after the festive season. He does not have collateral to offer at this time.

========== L006 ==========

V1:
Kofi, a 22-year-old, is requesting GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business from Dubai. He has no prior experience, but claims to be "business-minded" and promises to repay the loan in one year when his businesses are successful. He offers no collateral, but assures that he is trustworthy.

V2:
Kofi has applied for a loan of GHS 50,000 to start three business ventures: a car washing business, a provision shop, and a phone import business. He is 22 years old and claims to be business-minded, although he has not yet started any of these businesses. Kofi intends to repay the loan within one year, expecting his businesses to be successful by then. He does not have collateral to offer, but assures that he is trustworthy.

## Student Reasoning — Summarization Prompts

**1. Problems with V1 and how V2 fixed them**

- **V1 sometimes added assumptions.** For L006, V1 said Kofi had **"no prior experience"**, but the letter only says he has not started the businesses yet.
- V1 also added **"as assurance"** to Kofi's trustworthiness, which was not explicitly stated.
- **V2 was more factual and neutral**, avoided unnecessary assumptions, and followed the 3 to 4 sentence constraint.

**2. Why is "no invented details" important?**

Loan decisions should be based only on the applicant's actual information. Invented details could unfairly affect a person's loan decision.

This failure mode is called **hallucination** in LLMs.

In [12]:
# TODO: Write EXTRACT_PROMPT — a template that instructs the model to return ONLY a JSON
#   object with EXACTLY these keys:
#     applicant_name (string), amount_ghs (number), purpose (string),
#     monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean),
#     repayment_months (number or null)
#   Techniques to use:
#     - explicit schema in the prompt
#     - ONE worked example (few-shot) using a letter you write yourself (not from LETTERS!)
#     - "If a field is not stated in the letter, use null. Do not guess."
#     - temperature=0
EXTRACT_SYSTEM_PROMPT = """You extract structured information from loan applications.

Return ONLY a valid JSON object with EXACTLY these keys:
{
  "applicant_name": "string",
  "amount_ghs": number,
  "purpose": "string",
  "monthly_profit_ghs": number or null,
  "has_collateral_or_guarantor": boolean,
  "repayment_months": number or null
}

Rules:
- If a field is not stated in the letter, use null.
- Do not guess or invent information.
- amount_ghs, monthly_profit_ghs, and repayment_months must be numbers.
- has_collateral_or_guarantor must be true or false.
- Return ONLY the JSON object. No explanation or markdown.

Example:

Letter:
"My name is Ama Asante. I need GHS 5,000 to buy stock for my shop.
I make GHS 700 profit per month and can repay in 10 months.
My brother will guarantee the loan."

JSON:
{
  "applicant_name": "Ama Asante",
  "amount_ghs": 5000,
  "purpose": "buy stock for my shop",
  "monthly_profit_ghs": 700,
  "has_collateral_or_guarantor": true,
  "repayment_months": 10
}
"""

EXTRACT_PROMPT = """Extract the required information from this loan application.

Loan application:
{letter_text}
"""

# TODO: Write extract_fields(letter_text) that calls the LLM, strips any ```json fences,
#   json.loads() the result, and returns a dict. Handle parse failures gracefully
#   (return None and print a warning).
def extract_fields(letter_text):
    response = ask_llm(
        EXTRACT_PROMPT.format(letter_text=letter_text),
        system_prompt=EXTRACT_SYSTEM_PROMPT,
        temperature=0.0
    )

    result = response.choices[0].message.content.strip()

    # Remove markdown JSON fences if the model adds them
    if result.startswith("```json"):
        result = result[7:]
    elif result.startswith("```"):
        result = result[3:]

    result = result.removesuffix("```")

    result = result.strip()

    try:
        data = json.loads(result)
        return data
    except json.JSONDecodeError:
        print("Warning: Could not parse LLM response as JSON.")
        return None

# TODO: Run it on ALL SIX letters; collect results into a pandas DataFrame (one row per
#   letter) and display it.
results = []

for letter_id, letter_text in LETTERS.items():
    extracted = extract_fields(letter_text)

    if extracted is not None:
        extracted["letter_id"] = letter_id
        results.append(extracted)

df = pd.DataFrame(results)

# Put letter_id first
columns = ["letter_id"] + [
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]

df = df[columns]

display(df)

,letter_id,applicant_name,amount_ghs,purpose,monthly_profit_ghs,has_collateral_or_guarantor,repayment_months
0,L001,Akosua Mensah,8000,buy a deep freezer and expand into frozen foods,900.0,True,20.0
1,L002,Kwame Boateng,25000,repair my trotro engine and settle some person...,NaN,False,NaN
2,L003,Efua Darko,15000,purchase two industrial sewing machines and fa...,2800.0,True,15.0
3,L004,Yaw Owusu,12000,for feed and 500 new layers for my poultry farm,1500.0,True,18.0
4,L005,Adenta Women's Weaving Cooperative,30000,buy a bulk order of yarn directly from the fac...,NaN,True,16.0
5,L006,Kofi,50000,"start a car washing business, a provision shop...",NaN,False,12.0

## Student Reasoning — Structured Extraction

**1. Why must the few-shot example be different?**

Using one of the six letters could make the model memorize or copy information from the data being evaluated. A separate example tests whether the prompt works generally.

**2. Why use `null, do not guess`?**

It prevents the model from making up missing information. Without this instruction, the model may try to **infer or invent** values that were not stated.

**3. Why use temperature = 0?**

For extraction, we want **consistent and predictable results**, so temperature `0` is appropriate. For creative tasks, a higher temperature can be better because it produces more varied and creative responses.

In [15]:
# TODO: Write BRIEF_PROMPT — it receives the letter AND your extracted JSON, and must output:
#     1. Strengths (bullet points, grounded in the letter)
#     2. Risks / red flags (bullet points)
#     3. Missing information the officer should request
#     4. Suggested next step (e.g. "invite for interview", "request documents",
#        "flag for senior review") — NOT "approve" or "reject".
#   Give the model an explicit instruction that final decisions are made by humans.
BRIEF_SYSTEM_PROMPT = """You are an assistant to a microfinance loan officer.

Your task is to analyze a loan application and provide a factual decision-support brief.

Your response must contain exactly these four sections:

1. Strengths
- Bullet points grounded only in the letter.

2. Risks / red flags
- Bullet points based only on information in the letter.

3. Missing information
- List important information the loan officer should request.

4. Suggested next step
- Suggest an action such as "invite for interview", "request documents",
  or "flag for senior review".
- Do NOT recommend approving or rejecting the loan.

Important:
- Do not invent or assume information.
- Clearly distinguish stated facts from missing information.
- Final loan decisions are made by human loan officers, not by the AI.
"""

BRIEF_PROMPT = """Analyze this loan application using the extracted information below.

Loan application:
{letter_text}

Extracted information:
{extracted_json}
"""

# TODO: Generate briefs for ALL SIX letters. Print the briefs for L001, L002, and L006 —
#   three very different applications.
briefs = {}

for letter_id, letter_text in LETTERS.items():
    row = df[df["letter_id"] == letter_id]

    if row.empty:
        briefs[letter_id] = "Extraction failed; no brief generated."
        continue

    extracted_json = row.iloc[0].to_dict()

    response = ask_llm(
        BRIEF_PROMPT.format(
            letter_text=letter_text,
            extracted_json=json.dumps(extracted_json, indent=2)
        ),
        system_prompt=BRIEF_SYSTEM_PROMPT,
        temperature=0.0
    )

    briefs[letter_id] = response.choices[0].message.content
    
# Print the briefs for L001, L002, and L006
for letter_id in ["L001", "L002", "L006"]:
    print()
    print(f"==== BRIEF — {letter_id} ====")
    print()
    print(briefs[letter_id])

==== BRIEF — L001 ====

## Step 1: Strengths
- The applicant, Akosua Mensah, has 12 years of experience selling provisions at Makola Market, indicating stability and knowledge in her business.
- She has a steady monthly profit of GHS 900 from her current stall.
- Akosua has saved GHS 2,500 over two years with the susu scheme, demonstrating her ability to save and commit to financial obligations.
- She has a guarantor, her sister, who is a teacher, potentially providing an additional layer of financial security.
- The applicant has a clear plan for repayment, proposing to pay GHS 450 monthly over 20 months.

## Step 2: Risks / red flags
- The loan amount of GHS 8,000 is significant compared to her monthly profit and savings, which might pose a risk if her business expansion does not generate enough additional income.
- There is no detailed information on how the expansion into frozen foods will affect her current business operations or profitability.
- The repayment plan relies on her ability to maintain or increase her current profit level, which may be affected by various market factors.

## Step 3: Missing information
- Detailed business plan for the expansion into frozen foods, including projected additional income and expenses.
- Information on the sister's (guarantor's) financial stability and ability to cover the loan if Akosua defaults.
- Current market analysis for frozen foods at Makola Market to assess demand and competition.
- Akosua's current debt obligations, if any, to understand her overall financial situation.
- Specifics about the deep freezer and its cost to ensure the loan amount is appropriate.

## Step 4: Suggested next step
Invite Akosua Mensah for an interview to discuss her business plan in more detail, including the potential risks and benefits of expanding into frozen foods, and to gather the missing information necessary for a thorough loan assessment.

==== BRIEF — L002 ====

## Step 1: Strengths
- The applicant, Kwame Boateng, has a clear purpose for the loan, which is to repair his trotro engine and settle personal debts.
- He is a commercial driver, implying he has a source of income.

## Step 2: Risks / red flags
- The applicant mentions that business has been slow, which could impact his ability to repay the loan.
- He does not have collateral or a guarantor, increasing the risk for the lender.
- The repayment plan is vague, with the applicant stating he can pay back "whenever the money comes," which lacks specificity and commitment.

## Step 3: Missing information
- Monthly profit in GHS to assess the applicant's financial stability and ability to repay the loan.
- Specific details on how he plans to repay the loan, including the repayment period and amount.
- Information on his personal debts and how they will be settled with part of the loan.
- Details on his trotro business, such as the number of vehicles, daily operations, and potential for growth after the festive season.

## Step 4: Suggested next step
- Invite the applicant for an interview to gather more detailed information about his business, financial situation, and repayment plan, and to discuss the risks and expectations associated with the loan.

==== BRIEF — L006 ====

## Step 1: Strengths
- The applicant, Kofi, is 22 and describes himself as "full of energy", which could be an advantage in managing and growing a business.
- Kofi has multiple business ideas (car washing, provision shop, and importing phones), which could diversify his income streams.
- He expresses confidence in his business abilities, mentioning that his friends consider him "very business minded".

## Step 2: Risks / red flags
- The applicant lacks experience in the proposed businesses, as he mentions that he has not started any of them yet.
- There is no collateral or guarantor provided to secure the loan.
- The repayment plan is based on the expectation that the businesses will be "booming" within a year, which is a high-risk assumption.
- The applicant's self-assessment of being "trustworthy" is subjective and not a tangible guarantee for loan repayment.

## Step 3: Missing information
- Detailed business plans for each of the proposed ventures.
- Market research or analysis to support the viability of the businesses.
- Financial projections, including estimated monthly profits and expenses.
- Information about Kofi's educational background, work experience, or any relevant skills.
- Credit history or previous loan repayment records.

## Step 4: Suggested next step
- Invite Kofi for an interview to discuss his business ideas in more detail, assess his understanding of the market and financial aspects of the proposed ventures, and evaluate his overall creditworthiness.

## Student Reasoning — Decision Support

**1. Compare L003 and L006**

The system correctly identified the main differences:

- **L003:** It identified strong business experience, regular profit, savings history, and a fixed deposit as strengths. It also suggested verifying the business plan and supporting documents.
- **L006:** It identified major risks such as no existing business, no collateral, no proven cash flow, and an uncertain repayment plan.

Overall, the briefs correctly reflected that **L003 is stronger while L006 carries much higher risk**.

**2. Why forbid "approve/reject"?**

- **Practical reason:** The AI can make mistakes or miss important information, so a human loan officer should make the final decision.
- **Ethical reason:** Loan decisions can seriously affect people's lives, so giving an AI full authority could lead to unfair or biased decisions.

### Part 3.4 — Commit your prompt templates
Commit hash: 4f711bf48aecf088a423c412d3b0986ef95d028c

In [16]:
# TODO: For the three letters in GOLD, compare your extracted DataFrame to the gold values
#   field by field. Compute per-field accuracy across the three letters
#   (name matching can be case-insensitive; numbers must match exactly).


# Compare extracted values with GOLD values field by field.
fields = [
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]

rows = []

for field in fields:
    row = {"field": field}
    correct = 0

    for letter_id in GOLD:
        predicted = df.loc[df["letter_id"] == letter_id, field].iloc[0]
        expected = GOLD[letter_id][field]

        # Name comparison is case-insensitive
        if field == "applicant_name":
            match = str(predicted).strip().lower() == str(expected).strip().lower()
        else:
            match = predicted == expected

        row[letter_id] = "✓" if match else "✗"

        if match:
            correct += 1

    row["accuracy"] = f"{correct}/3 ({correct / 3:.0%})"
    rows.append(row)

accuracy_df = pd.DataFrame(rows)

# TODO: Display a small table: rows = fields, columns = L001 / L003 / L006 / accuracy.
display(accuracy_df)

                         field L001 L003 L006    accuracy
0               applicant_name    ✓    ✓    ✓  3/3 (100%)
1                   amount_ghs    ✓    ✓    ✓  3/3 (100%)
2                      purpose    ✗    ✗    ✗    0/3 (0%)
3           monthly_profit_ghs    ✓    ✓    ✗   2/3 (67%)
4  has_collateral_or_guarantor    ✓    ✓    ✓  3/3 (100%)
5             repayment_months    ✓    ✓    ✓  3/3 (100%)

In [17]:
# TODO: Run extract_fields() on letter L004 FIVE times at temperature=0 and FIVE times at
#   temperature=1.0.
def extract_fields(letter_text, temperature=0.0):
    response = ask_llm(
        EXTRACT_PROMPT.format(letter_text=letter_text),
        system_prompt=EXTRACT_SYSTEM_PROMPT,
        temperature=temperature
    )

    result = response.choices[0].message.content.strip()

    if result.startswith("```json"):
        result = result[7:]
    elif result.startswith("```"):
        result = result[3:]

    result = result.removesuffix("```")

    try:
        return json.loads(result.strip())
    except json.JSONDecodeError:
        print("Warning: Could not parse LLM response as JSON.")
        return None

# TODO: For each temperature, report how many of the 5 runs produced (a) valid JSON and
#   (b) identical values across runs. A simple approach: json.dumps(result, sort_keys=True)
#   and count unique strings.
for temperature in [0.0, 1.0]:
    results = []

    for _ in range(5):
        result = extract_fields(LETTERS["L004"], temperature=temperature)
        results.append(result)

    valid_results = [r for r in results if r is not None]

    unique_results = {
        json.dumps(r, sort_keys=True)
        for r in valid_results
    }

    print(f"\nTemperature = {temperature}")
    print(f"Valid JSON: {len(valid_results)}/5")
    print(f"Identical values across runs: {len(unique_results) == 1}")
    print(f"Unique result sets: {len(unique_results)}")

Temperature = 0.0
Valid JSON: 5/5
Identical values across runs: True
Unique result sets: 1

Temperature = 1.0
Valid JSON: 5/5
Identical values across runs: True
Unique result sets: 1

In [18]:
# TODO: Design TWO adversarial tests and run them:
#   Test 1 — Ask your summarizer a question about a detail that is NOT in a letter
#     (e.g. "What is the applicant's credit score?"). Does it admit the information is
#     absent, or does it invent one?
#   Test 2 — Feed your extractor an EMPTY or IRRELEVANT text (e.g. a weather report).
#     Does it return nulls, or does it fabricate an applicant?
# Test 1: Ask for information that is NOT in the letter.

adversarial_summary_prompt = """Summarize this loan application.
Also state the applicant's credit score.

Loan application:
{letter_text}
"""

response = ask_llm(
    adversarial_summary_prompt.format(letter_text=LETTERS["L002"]),
    system_prompt=SUMMARY_SYSTEM_V2,
    temperature=0.0
)

test1_output = response.choices[0].message.content

# Test 2: Give the extractor completely irrelevant text.

weather_report = """
Today's weather will be partly cloudy with temperatures around 29°C.
There is a chance of rain in the afternoon, with moderate winds expected.
"""

test2_result = extract_fields(weather_report)

# TODO: Record the outputs verbatim below and label each PASS or FAIL.
print("TEST 1: Missing Information")
print(test1_output)

print()

print("\nTEST 2: Irrelevant Input")
print(test2_result)

TEST 1: Missing Information
Kwame Boateng, a commercial driver in Kumasi, has applied for a loan of GHS 25,000 to repair his trotro engine and settle personal debts. He mentions that business has been slow but expects it to improve after the festive season. The applicant does not have collateral to offer at the moment. The credit score of the applicant is not provided in the loan application.


TEST 2: Irrelevant Input
{'applicant_name': None, 'amount_ghs': None, 'purpose': None, 'monthly_profit_ghs': None, 'has_collateral_or_guarantor': None, 'repayment_months': None}

## Student Reasoning — Evaluation Results

**1. Extraction accuracy**

The overall accuracy was **78% (14/18 fields)**.

- **100%:** applicant name, loan amount, collateral/guarantor, repayment period.
- **67%:** monthly profit.
- **0%:** purpose, which was the hardest field. The model likely struggled because the purpose descriptions in the letters did not exactly match the wording expected in the `GOLD` labels.

**2. Reliability and temperature**

Both temperatures produced **5/5 valid JSON results with identical values across all runs**. This shows that the extraction was stable in this test. However, production systems should still prefer **low temperature** for predictable and consistent structured extraction.

**3. Hallucination testing**

The system **passed both adversarial tests**. It admitted that the credit score was not provided and returned `null` for all fields when given an irrelevant weather report.

To reduce hallucination risk further, we can use explicit **"do not guess, use null"** instructions, strict JSON schemas, validation rules, and human review for important decisions.

## Student Reasoning — Appropriateness

**1. Who could be unfairly harmed?**

Applicants who write poorly in English could be unfairly judged even if they have strong businesses. The AI may misunderstand their applications and identify incorrect risks, leading to unfair loan decisions.

**2. What are the implications of using a third-party API?**

Sending loan letters to a third-party API could expose sensitive personal and financial information. Before deployment, I would check Ghanaian data-protection requirements, the provider's privacy and data-retention policies, where the data is stored, and whether the institution has permission to transfer the data outside Ghana.

**3. Two production safeguards**

1. **Human review:** An AI recommendation should never automatically approve or reject a loan. A qualified loan officer must review the evidence and make the final decision.
2. **Monitoring and appeals:** Log AI outputs and decisions for auditing, monitor for errors or bias, and provide applicants with a way to challenge or appeal decisions.

## Section 5 — Reflection

### 1. Prompting as engineering

Prompt iteration is similar to tuning model hyperparameters because both involve testing, evaluating results, and adjusting settings to improve performance. The difference is that prompt engineering changes the **instructions and context given to the model**, while hyperparameter tuning changes how the model itself learns or behaves during training.

### 2. Trust

I would **not trust the system to run unattended** because the extraction evaluation achieved only **78% accuracy**, with the `purpose` field scoring **0%**. This shows that even when the system produces valid and consistent output, it can still extract important information incorrectly.

### 3. Cost and scale

From my API usage, one call used roughly **500 tokens**. At that rate, 1,000 applications would require about **500,000 tokens** for one LLM call per application. If multiple calls are needed for each application, usage would increase significantly, so provider pricing, token limits, reliability, and data privacy would be important factors when choosing a provider.

### 4. Looking back at the course

For this task, calling a foundation-model API is better than training our own model because it provides strong language understanding without requiring a large dataset, expensive training, and significant computing resources. However, training our own model may be better when we need **full control, specialized behavior, lower long-term costs at very large scale, or strict data privacy**.